version: '3.4'

services:
  inventario:
    image: inventario
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /productos:/usr/src/app
    env_file: .env
    environment:
      - DEBUG=1
      - SECRET_KEY= $SECRET_KEY
      - ALLOWED_HOSTS= $ALLOWED_HOSTS
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    #tty: true
    #stdin_open: true

    
  db:
    image: postgres:15
    container_name: productos
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
